apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"praphul5dep1"},"name":"praphul5dep1","namespace":"praphul"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"praphul5dep1"}},"strategy":{},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"praphul5dep1"}},"spec":{"containers":[{"image":"dockerashu/oraclewebappashu2020317:v1","name":"oraclewebappashu2020317"}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    app: praphul5dep1
  name: praphul5dep1
  selfLink: /apis/apps/v1/namespaces/praphul/deployments/praphul5dep1
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: praphul5dep1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: praphul5dep1
    spec:
      containers:
      - image: dockerashu/oraclewebappashu2020317:v1
        imagePullPolicy: IfNotPresent
        name: oraclewebappashu2020317
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
