apiVersion: v1
kind: Service
metadata:
  name: praphulsvc1 #My service name
spec:
  ports:
  - name: mypraphul
    port: 80
    protocol: TCP
    targetPort: 80 #same as container port in the pod
  selector:
    x: praphulwebapp
  type: NodePort
